name: Deploy Infrastructure to Azure

on:
  push:
    branches: [ main ]
    paths: 
      - 'infra/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'infra/**'
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  AZURE_LOCATION: westeurope

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Deploy Key Vault
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./infra/key-vault.bicep
        parameters: ./infra/key-vault.parameters.json
        failOnStdErr: false
        deploymentName: key-vault-deployment
        
    - name: Deploy Main Infrastructure
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.AZURE_RESOURCE_GROUP }}
        template: ./infra/main.bicep
        parameters: ./infra/main.parameters.json
        failOnStdErr: false
        deploymentName: main-infrastructure-deployment
        
    - name: Get Key Vault deployment outputs
      id: keyvault-deployment
      run: |
        echo "Getting Key Vault deployment outputs..."
        az deployment group show \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name key-vault-deployment \
          --query properties.outputs \
          --output json
          
    - name: Get main deployment outputs
      id: main-deployment
      run: |
        echo "Getting main deployment outputs..."
        az deployment group show \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name main-infrastructure-deployment \
          --query properties.outputs \
          --output json
          
    - name: Display deployment results
      run: |
        echo "Infrastructure deployment completed successfully!"
        echo "Key Vault deployed and configured with service principal access"
        echo "Container Registry credentials stored securely in Key Vault"
        echo "Web App configured to use Key Vault secrets for ACR authentication"
        echo "Container Registry: ${{ steps.main-deployment.outputs.containerRegistryName }}"
        echo "Web App URL: ${{ steps.main-deployment.outputs.webAppUrl }}"
        echo "Key Vault: ${{ steps.keyvault-deployment.outputs.keyVaultName }}" 